version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
     - image: cimg/base:stable
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Install Front-End
          command: npm run install:frontend
      - run:
          name: Install Back-end
          command: npm run install:backend
      - run:
          name: Build Front-End
          command: npm run build:frontend
      - run:
          name: Build Back-end
          command: npm run build:backend
      - run:
          name: Deploy Front-End
          command: npm run deploy:frontend
      - run:
          name: Deploy Back-end
          command: npm run deploy:backend
workflows:
    build-deploy:
      jobs:
        - build:
            filters:
              branches:
                only: 
                  - main
